version: '3'
services:
  ympd:
    container_name: ympd
    restart: always
    image: ghcr.io/hifiberry/extension_ympd:latest
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    devices:
      - /dev/snd:/dev/snd
    group_add:
      - 2001
    ports:
      - 9999:9999
